name = "dj-cansu-dev-backend"
main = "src/index.ts"
compatibility_date = "2024-10-28"
compatibility_flags = ["nodejs_compat"]

# [vars]
# MY_VAR = "my-variable"

[[r2_buckets]]
binding = "S3Bucket"
bucket_name = "cansu-dev-dj"

[observability]
enabled = true
head_sampling_rate = 1
