/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DjImport } from './routes/dj'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const DjRoute = DjImport.update({
  id: '/dj',
  path: '/dj',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dj': {
      id: '/dj'
      path: '/dj'
      fullPath: '/dj'
      preLoaderRoute: typeof DjImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dj': typeof DjRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dj': typeof DjRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dj': typeof DjRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dj'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dj'
  id: '__root__' | '/' | '/dj'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DjRoute: typeof DjRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DjRoute: DjRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dj"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dj": {
      "filePath": "dj.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
